import {daySpan} from './time-bars.js';
const API='https://portal.3dvr.tech/family-calendar-api';
const $=id=>document.getElementById(id);
const fragment=new URLSearchParams(location.hash.slice(1));
const room=fragment.get('room'),key=fragment.get('key');
const labels={'thomas-work':'Thomas · work','partner-work':'Partner · work','thomas-event':'Thomas · event','partner-event':'Partner · event',together:'Together'};
let data=null,viewDate=new Date(),selected=dateKey(new Date()),mode='month',saving=false;
viewDate=new Date(viewDate.getFullYear(),viewDate.getMonth(),1);
function dateKey(date){return [date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-');}
function localDate(value){return new Date(value+'T12:00:00');}
function dayLabel(value){return localDate(value).toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric',year:'numeric'});}
function clock(t){return new Date('2000-01-01T'+t).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'});}
function range(e){const time=e.startTime&&e.endTime?clock(e.startTime)+'–'+clock(e.endTime):e.startTime?clock(e.startTime):'Flexible / all day';return e.startDate===e.endDate?time:e.startDate.slice(5)+'–'+e.endDate.slice(5)+' · '+time;}
function visible(){const active=new Set([...document.querySelectorAll('.filters input:checked')].map(x=>x.value));return (data?.events||[]).filter(e=>active.has(e.category)).sort((a,b)=>a.startDate.localeCompare(b.startDate)||a.startTime.localeCompare(b.startTime));}
function onDay(events,date){return events.filter(e=>e.startDate<=date&&e.endDate>=date);}
function el(tag,text,className){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;}
async function request(path='',method='GET',body){const res=await fetch(API+'/rooms/'+room+path,{method,headers:{Authorization:'Bearer '+key,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});const value=await res.json();if(!res.ok){const err=new Error(value.error||'Unable to reach calendar');err.status=res.status;throw err;}return value;}
function status(message){$('status').textContent=message;}
async function refresh(){try{data=await request();$('locked').hidden=true;$('planner').hidden=false;$('share').hidden=false;$('print').hidden=false;render();status('Shared calendar · '+(data.updatedAt?'saved '+new Date(data.updatedAt).toLocaleString('en-US',{timeZone:'America/Los_Angeles',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'ready'));}catch(e){status(e.message);if(!data)$('locked').querySelector('p').textContent=e.message;throw e;}}
function row(e){const node=el('div',undefined,'event-row');node.append(el('span',undefined,'dot '+e.category));const body=el('div',undefined,'event-body');body.append(el('strong',e.title+(e.tentative?' · tentative':'')),el('div',range(e)+' · '+labels[e.category],'event-meta'));if(e.notes)body.append(el('p',e.notes));node.append(body);const edit=el('button','Edit','edit');edit.type='button';edit.onclick=()=>openEditor(e);node.append(edit);return node;}
function render(){const events=visible(),year=viewDate.getFullYear(),month=viewDate.getMonth();$('month').textContent=viewDate.toLocaleDateString('en-US',{month:'long',year:'numeric'});$('grid').replaceChildren();const start=new Date(year,month,1);start.setDate(start.getDate()-((start.getDay()+6)%7));const today=dateKey(new Date());for(let n=0;n<42;n++){const date=new Date(start);date.setDate(start.getDate()+n);const d=dateKey(date),items=onDay(events,d),button=el('button',undefined,'day'+(date.getMonth()!==month?' outside':'')+(d===selected?' selected':'')+(d===today?' is-today':''));button.type='button';button.setAttribute('aria-label',dayLabel(d)+', '+items.length+' plans');button.setAttribute('aria-pressed',d===selected?'true':'false');button.append(el('span',String(date.getDate()),'day-number'));const bars=el('span',undefined,'day-bars');
items.forEach(e=>{
  const span=daySpan(e,d);if(!span)return;
  const track=el('span',undefined,'time-track'+(span.flexible?' flexible':'')+(e.tentative?' tentative':''));
  const description=e.title+' · '+(span.flexible?'Flexible hours':range(e))+(e.tentative?' · tentative':'');
  track.title=description;track.setAttribute('role','img');track.setAttribute('aria-label',description);
  const fill=el('span',undefined,'time-fill '+e.category);
  fill.style.left=span.left+'%';fill.style.width=span.width+'%';
  track.append(fill);bars.append(track);
});
button.append(bars);items.slice(0,3).forEach(e=>{const item=el('span',e.title,'mini '+e.category);item.append(el('small',e.tentative?'Tentative · '+range(e):range(e)));button.append(item);});if(items.length>3)button.append(el('small','+'+(items.length-3)+' more'));button.onclick=()=>{selected=d;render();$('day-panel').scrollIntoView({behavior:'smooth',block:'nearest'});};$('grid').append(button);}
$('day-title').textContent=dayLabel(selected);$('day-events').replaceChildren();const dayEvents=onDay(events,selected);if(!dayEvents.length)$('day-events').append(el('p','No plans recorded.','empty'));dayEvents.forEach(e=>$('day-events').append(row(e)));
$('agenda').replaceChildren();for(let n=1;n<=new Date(year,month+1,0).getDate();n++){const d=dateKey(new Date(year,month,n)),items=onDay(events,d);if(!items.length)continue;$('agenda').append(el('h2',dayLabel(d)));items.forEach(e=>$('agenda').append(row(e)));}if(!$('agenda').children.length)$('agenda').append(el('p','No plans recorded for this month.','empty'));
$('missing').hidden=data.events.some(e=>e.category==='partner-work');$('snapshot').textContent='Google Calendar snapshot: '+new Date(data.snapshotAt).toLocaleString('en-US',{timeZone:'America/Los_Angeles',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})+'. Work shifts marked tentative are unpublished. This page shares edits live; Google imports are a snapshot.';
renderConflicts();$('month-panel').hidden=mode!=='month';$('agenda').hidden=mode!=='agenda';$('day-panel').hidden=mode!=='month';$('month-view').setAttribute('aria-pressed',String(mode==='month'));$('agenda-view').setAttribute('aria-pressed',String(mode==='agenda'));}
function renderConflicts(){const box=$('conflicts');box.replaceChildren();const events=data.events;const monthStart=dateKey(viewDate),monthEnd=dateKey(new Date(viewDate.getFullYear(),viewDate.getMonth()+1,0));const inMonth=events.filter(e=>e.startDate<=monthEnd&&e.endDate>=monthStart);const messages=[];for(let i=0;i<inMonth.length;i++)for(let j=i+1;j<inMonth.length;j++){const a=inMonth[i],b=inMonth[j];if(a.startDate>b.endDate||b.startDate>a.endDate)continue;const trip=[a,b].find(e=>e.category==='together'&&/Mexico/i.test(e.title));const other=trip===a?b:a;if(trip&&other.category==='partner-event')messages.push({title:'Mexico trip + partner’s event',text:dayLabel(other.startDate)+': '+other.title+' overlaps the trip dates. Plan this together.'});if(a.category.startsWith('thomas')&&b.category.startsWith('thomas')&&a.category!==b.category&&a.startTime&&a.endTime&&b.startTime&&b.endTime&&a.startDate===b.startDate&&a.startTime<b.endTime&&b.startTime<a.endTime)messages.push({title:'Appointment + work overlap',text:dayLabel(a.startDate)+': '+a.title+' ('+range(a)+') and '+b.title+' ('+range(b)+').'});}
for(const m of messages){const card=el('div',undefined,'notice warning');card.append(el('strong',m.title),el('span',m.text));box.append(card);}}
function openEditor(e){$('event-form').reset();$('event-id').value=e?.id||'';$('editor-title').textContent=e?'Edit plan':'Add a plan';$('title').value=e?.title||'';$('category').value=e?.category||'together';$('start-date').value=e?.startDate||selected;$('end-date').value=e?.endDate||selected;$('start-time').value=e?.startTime||'';$('end-time').value=e?.endTime||'';$('notes').value=e?.notes||'';$('tentative').checked=!!e?.tentative;$('delete').hidden=!e;$('form-error').textContent='';$('editor').showModal();$('title').focus();}
async function save(events){saving=true;$('save').disabled=true;$('delete').disabled=true;try{data=await request('','PUT',{revision:data.revision,events});$('editor').close();render();status('Saved together.');}catch(e){$('form-error').textContent=e.message;if(e.status===409){await refresh();$('form-error').textContent='Someone changed the calendar. Review their updates, then save again.';}}finally{saving=false;$('save').disabled=false;$('delete').disabled=false;}}
$('event-form').onsubmit=async event=>{event.preventDefault();const id=$('event-id').value||crypto.randomUUID();const existing=data.events.find(e=>e.id===id);const entry={id,title:$('title').value,category:$('category').value,startDate:$('start-date').value,endDate:$('end-date').value,startTime:$('start-time').value,endTime:$('end-time').value,notes:$('notes').value,tentative:$('tentative').checked,source:existing?.source||'Together'};if(entry.endDate<entry.startDate){$('form-error').textContent='End date must be on or after the start.';return;}await save([...data.events.filter(e=>e.id!==id),entry]);};
$('delete').onclick=()=>{if(confirm('Delete this plan from your shared calendar?'))save(data.events.filter(e=>e.id!==$('event-id').value));};
$('start-date').onchange=()=>{if($('end-date').value<$('start-date').value)$('end-date').value=$('start-date').value;};
$('add').onclick=()=>openEditor();$('cancel').onclick=()=>$('editor').close();$('prev').onclick=()=>{viewDate.setMonth(viewDate.getMonth()-1);render();};$('next').onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);render();};$('today').onclick=()=>{const now=new Date();viewDate=new Date(now.getFullYear(),now.getMonth(),1);selected=dateKey(now);render();};$('month-view').onclick=()=>{mode='month';render();};$('agenda-view').onclick=()=>{mode='agenda';render();};document.querySelectorAll('.filters input').forEach(input=>input.onchange=render);$('print').onclick=()=>window.print();
$('share').onclick=async()=>{try{let shareKey=key;if(data.role==='owner'){const response=await request('/share','POST');shareKey=response.key;status('New partner link ready. Any older partner link has been replaced.');}const url=new URL(location.href);url.hash=new URLSearchParams({room,key:shareKey}).toString();$('share-link').value=url.href;$('revoke').hidden=data.role!=='owner';$('share-panel').hidden=false;$('share-panel').scrollIntoView({behavior:'smooth'});}catch(e){status(e.message);}};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('share-link').value);status('Partner link copied.');}catch{$('share-link').select();status('Select and copy the partner link.');}};$('revoke').onclick=async()=>{if(!confirm('Revoke this partner link? You can create a new one anytime.'))return;try{await request('/revoke','POST');$('share-panel').hidden=true;status('Partner access revoked.');}catch(e){status(e.message);}};$('close-share').onclick=()=>$('share-panel').hidden=true;
if(room&&/^[a-f0-9]{32}$/.test(room)&&key){refresh().catch(()=>{});setInterval(()=>{if(!saving&&!$('editor').open)refresh().catch(()=>{});},30000);}else{$('locked').hidden=false;}
